version: '3.8'

services:
  bot:
    build: ./bot
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NODE_ENV=production
      - WEBAPP_URL=http://localhost:5000
      - ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}
    volumes:
      - ./user_data:/app/user_data
    restart: unless-stopped

  webapp:
    build: ./webapp
    ports:
      - "5000:80"
    restart: unless-stopped
